---
apiVersion: v1
kind: Service
metadata:
  name: iris
spec:
  type: LoadBalancer
  selector:
    app: iris
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris
  labels:
    app: iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iris
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: iris
        image: us-central1-docker.pkg.dev/GOOGLE_PROJECT/maven-repo/images/iris:latest