name: Deploy Iris Classifier

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Code Checkout
      uses: actions/checkout@v2

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Install the gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        install_components: 'gke-gcloud-auth-plugin'

    - name: Build and push the Docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        # Generate a unique image tag (using Git commit hash)
        IMAGE_TAG=$(git rev-parse --short HEAD)
        
        # Full image name with tag
        IMAGE_NAME="us-central1-docker.pkg.dev/$GOOGLE_PROJECT/maven-repo/images/iris:$IMAGE_TAG"

        # Authenticate Docker with Artifact Registry
        gcloud auth configure-docker us-central1-docker.pkg.dev

        # Build and push the Docker image
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME

    - name: Deploy to GKE
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        # Configure kubectl to use the GKE cluster
        gcloud container clusters get-credentials ai-cluster --region us-central1

        # Update the image in resources.yaml with the new tag
        sed -i "s|image: us-central1-docker.pkg.dev/$GOOGLE_PROJECT/maven-repo/images/iris:.*|image: $IMAGE_NAME|" resources.yaml

        # Apply the updated resources.yaml to Kubernetes
        kubectl apply -f resources.yaml
